apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 211125297249.dkr.ecr.ap-south-1.amazonaws.com/frontend:3
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://ac0adc0b1cb4e43f49631f88361e4649-1105936280.ap-south-1.elb.amazonaws.com/api/tasks"
        ports:
        - containerPort: 3000
